export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const GET_USERS_DETAILS_REQUEST = 'GET_USERS_DETAILS_REQUEST';
export const GET_USERS_DETAILS_SUCCESS = 'GET_USERS_DETAILS_SUCCESS';
export const GET_USERS_DETAILS_FAILED = 'GET_USERS_DETAILS_FAILED';

export const ADD_TO_FAV = 'ADD_TO_FAV';
export const REMOVE_FROM_FAV = 'REMOVE_FROM_FAV';

export const FAV_ADD_REQUEST = 'FAV_ADD_REQUEST';
export const FAV_ADD_SUCCESS = 'FAV_ADD_SUCCESS';
export const FAV_ADD_FAILED = 'FAV_ADD_FAILED';