export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const GET_USERS_DETAILS_REQUEST = 'GET_USERS_DETAILS_REQUEST';
export const GET_USERS_DETAILS_SUCCESS = 'GET_USERS_DETAILS_SUCCESS';
export const GET_USERS_DETAILS_FAILED = 'GET_USERS_DETAILS_FAILED';